#!/usr/bin/env python

import sys
import subprocess


val = 0
if sys.argv[1] == "cpu":
    val = (subprocess.check_output('echo $((`cat /sys/class/thermal/thermal_zone0/temp|cut -c1-2`)).$((`cat /sys/class/thermal/thermal_zone0/temp|cut -c3-5`))', shell=True))
elif sys.argv[1] == 'gpu':
    val = (subprocess.check_output('/opt/vc/bin/vcgencmd measure_temp|cut -c6-9', shell=True))

print(val.strip())
