#!/usr/bin/env python

import os
import sys
import subprocess

if (sys.argv[1] == 'on'):
    subprocess.check_output('/opt/vc/bin/tvservice -p', shell=True)

    if len(sys.argv) > 2 and sys.argv[2] == "up":
        subprocess.check_output('sudo startx /usr/bin/graphical_launcher `fgconsole`', shell=True)

elif (sys.argv[1] == 'off'):
    subprocess.check_output('/opt/vc/bin/tvservice -o', shell=True)
